version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=doctor_syria.settings_simple
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=doctor_syria
      - MYSQL_USER=doctor_syria
      - MYSQL_PASSWORD=doctor_syria
      - MYSQL_ROOT_PASSWORD=doctor_syria_root
    ports:
      - "3306:3306"
    restart: unless-stopped

volumes:
  mysql_data:
