[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.prod"

[deploy]
startCommand = "gunicorn doctor_syria.wsgi:application --bind 0.0.0.0:$PORT --workers 4"
healthcheckPath = "/health/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
