# Generated by Django 4.2.17 on 2025-01-07 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical_records', '0002_improve_billing_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Medical Record', 'verbose_name_plural': 'Medical Records'},
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='chronic_diseases',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='emergency_phone',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='family_history',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='medications',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='chronic_conditions',
            field=models.TextField(blank=True, verbose_name='Chronic Conditions'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10, verbose_name='Marital Status')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('emergency_contact_name', models.CharField(max_length=255, verbose_name='Emergency Contact Name')),
                ('emergency_contact_phone', models.CharField(max_length=20, verbose_name='Emergency Contact Phone')),
                ('address', models.TextField(verbose_name='Address')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='Occupation')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.AlterField(
            model_name='followup',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='medical_records.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurances', to='medical_records.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_invoices', to='medical_records.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='medical_records.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to='medical_records.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='medicalvisit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_visits', to='medical_records.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='medical_records.patient', verbose_name='Patient'),
        ),
    ]
