# Generated by Django 5.1.4 on 2025-01-06 16:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models

import accounts.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "مدير"),
                            ("doctor", "طبيب"),
                            ("nurse", "ممرض"),
                            ("pharmacist", "صيدلي"),
                            ("lab_technician", "فني مختبر"),
                            ("receptionist", "موظف استقبال"),
                            ("patient", "مريض"),
                        ],
                        default="patient",
                        max_length=20,
                        verbose_name="الدور",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        unique=True,
                        validators=[accounts.models.validate_phone_number],
                        verbose_name="رقم الهاتف",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="العنوان")),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الميلاد"
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_pictures/",
                        verbose_name="الصورة الشخصية",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=100, verbose_name="التخصص"),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        validators=[accounts.models.validate_license_number],
                        verbose_name="رقم الترخيص",
                    ),
                ),
                (
                    "two_factor_enabled",
                    models.BooleanField(
                        default=False, verbose_name="تفعيل المصادقة الثنائية"
                    ),
                ),
                (
                    "two_factor_secret",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="سر المصادقة الثنائية",
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(
                        default=False, verbose_name="تم التحقق من البريد"
                    ),
                ),
                (
                    "failed_login_attempts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="محاولات تسجيل الدخول الفاشلة"
                    ),
                ),
                (
                    "account_locked_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="الحساب مقفل حتى"
                    ),
                ),
                (
                    "last_password_change",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="آخر تغيير لكلمة المرور",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="آخر عنوان IP"
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر نشاط"
                    ),
                ),
                (
                    "device_info",
                    models.JSONField(default=dict, verbose_name="معلومات الأجهزة"),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="الباركود"
                    ),
                ),
                (
                    "id_card",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="البطاقة التعريفية",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستخدم",
                "verbose_name_plural": "المستخدمين",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="MedicalInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=5,
                        verbose_name="فصيلة الدم",
                    ),
                ),
                ("allergies", models.TextField(blank=True, verbose_name="الحساسية")),
                (
                    "chronic_diseases",
                    models.TextField(blank=True, verbose_name="الأمراض المزمنة"),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="جهة اتصال للطوارئ"
                    ),
                ),
                (
                    "emergency_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        validators=[accounts.models.validate_phone_number],
                        verbose_name="هاتف الطوارئ",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_info",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "معلومات طبية",
                "verbose_name_plural": "معلومات طبية",
            },
        ),
    ]
