# Generated by Django 5.1.4 on 2025-01-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمين'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير'), ('doctor', 'طبيب'), ('nurse', 'ممرض'), ('pharmacist', 'صيدلي'), ('lab_technician', 'فني مختبر'), ('receptionist', 'موظف استقبال'), ('patient', 'مريض')], default='patient', max_length=20, verbose_name='الدور'),
        ),
    ]
