# Generated by Django 4.2.8 on 2025-01-08 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saas_core", "0001_initial"),
        ("saas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clinics",
                to="saas_core.tenant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clinicservice",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clinic_services",
                to="saas_core.tenant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clinicequipment",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clinic_equipment",
                to="saas_core.tenant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medicine",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medicines",
                to="saas_core.tenant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manufacturers",
                to="saas_core.tenant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="saas_core.tenant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="commerceorder",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commerce_orders",
                to="saas_core.tenant",
            ),
            preserve_default=False,
        ),
    ]
