# Generated by Django 4.2.8 on 2025-01-08 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saas_core", "0001_initial"),
        ("saas", "0002_auto_20250108_1300"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateTimeField()),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("auto_renew", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubscriptionFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50)),
                ("value", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Usage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.JSONField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="doctor",
            options={"ordering": ["user__first_name", "user__last_name"]},
        ),
        migrations.AlterModelOptions(
            name="hospital",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="patient",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="doctor",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="doctors",
                to="saas_core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hospitals",
                to="saas_core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patients",
                to="saas_core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clinics",
                to="saas_core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="clinicequipment",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clinic_equipment",
                to="saas_core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="clinicservice",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clinic_services",
                to="saas_core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="commerceorder",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commerce_orders",
                to="saas_core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_items",
                to="saas_core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_transactions",
                to="saas_core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manufacturers",
                to="saas_core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="medicalcompany",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="medical_companies",
                to="saas_core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="medicalsupply",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="medical_supplies",
                to="saas_core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="medicines",
                to="saas_core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="saas_core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_orders",
                to="saas_core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="warehouses",
                to="saas_core.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(
                fields=["license_number"], name="saas_doctor_license_2fab77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(
                fields=["specialization"], name="saas_doctor_special_e38f21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hospital",
            index=models.Index(fields=["name"], name="saas_hospit_name_0657f2_idx"),
        ),
        migrations.AddIndex(
            model_name="hospital",
            index=models.Index(fields=["code"], name="saas_hospit_code_67055d_idx"),
        ),
        migrations.AddIndex(
            model_name="hospital",
            index=models.Index(fields=["city"], name="saas_hospit_city_466e9b_idx"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["name"], name="saas_patien_name_f7331c_idx"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["gender"], name="saas_patien_gender_be2be5_idx"),
        ),
        migrations.AddField(
            model_name="usage",
            name="feature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="saas.subscriptionfeature",
            ),
        ),
        migrations.AddField(
            model_name="usage",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usage",
                to="saas.subscription",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionfeature",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="features",
                to="saas.subscriptionplan",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="saas.subscriptionplan"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to="saas_core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="saas.subscription",
            ),
        ),
    ]
