# Generated by Django 4.2.17 on 2025-01-07 16:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم القسم")),
                ("description", models.TextField(blank=True, verbose_name="وصف القسم")),
                ("floor", models.CharField(max_length=50, verbose_name="الطابق")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "head_doctor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "doctor"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="headed_departments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "قسم",
                "verbose_name_plural": "الأقسام",
            },
        ),
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="اسم المستشفى")),
                (
                    "license_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم الترخيص"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="وصف المستشفى"),
                ),
                ("address", models.TextField(verbose_name="العنوان")),
                ("phone", models.CharField(max_length=20, verbose_name="رقم الهاتف")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="البريد الإلكتروني"),
                ),
                (
                    "website",
                    models.URLField(blank=True, verbose_name="الموقع الإلكتروني"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        upload_to="hospitals/logos/",
                        verbose_name="شعار المستشفى",
                    ),
                ),
                ("established_date", models.DateField(verbose_name="تاريخ التأسيس")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_24_hours",
                    models.BooleanField(default=False, verbose_name="خدمة 24 ساعة"),
                ),
                (
                    "has_emergency",
                    models.BooleanField(default=False, verbose_name="قسم طوارئ"),
                ),
                (
                    "has_ambulance",
                    models.BooleanField(default=False, verbose_name="خدمة إسعاف"),
                ),
                (
                    "bed_capacity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="عدد الأسرّة",
                    ),
                ),
                (
                    "icu_capacity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="عدد أسرّة العناية المركزة",
                    ),
                ),
                (
                    "operating_rooms",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="عدد غرف العمليات",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستشفى",
                "verbose_name_plural": "المستشفيات",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "staff_type",
                    models.CharField(
                        choices=[
                            ("doctor", "طبيب"),
                            ("nurse", "ممرض/ة"),
                            ("technician", "فني"),
                            ("admin", "إداري"),
                            ("other", "آخر"),
                        ],
                        max_length=20,
                        verbose_name="نوع الوظيفة",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ البدء")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الانتهاء"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to="hospitals.department",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospital_positions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "موظف",
                "verbose_name_plural": "الموظفين",
                "unique_together": {("hospital", "user", "department")},
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shift_type",
                    models.CharField(
                        choices=[
                            ("morning", "صباحي"),
                            ("evening", "مسائي"),
                            ("night", "ليلي"),
                            ("on_call", "تحت الطلب"),
                        ],
                        max_length=20,
                        verbose_name="نوع المناوبة",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="وقت البدء")),
                ("end_time", models.DateTimeField(verbose_name="وقت الانتهاء")),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="hospitals.department",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="hospitals.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "مناوبة",
                "verbose_name_plural": "المناوبات",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_number",
                    models.CharField(max_length=50, verbose_name="رقم الغرفة"),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("normal", "غرفة عادية"),
                            ("icu", "عناية مركزة"),
                            ("operation", "غرفة عمليات"),
                            ("emergency", "غرفة طوارئ"),
                            ("examination", "غرفة فحص"),
                        ],
                        max_length=20,
                        verbose_name="نوع الغرفة",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="السعة",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="متاحة"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="hospitals.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "غرفة",
                "verbose_name_plural": "الغرف",
                "unique_together": {("department", "room_number")},
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="اسم المعدات")),
                (
                    "serial_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="الرقم التسلسلي"
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(max_length=255, verbose_name="الشركة المصنعة"),
                ),
                ("model", models.CharField(max_length=100, verbose_name="الموديل")),
                ("purchase_date", models.DateField(verbose_name="تاريخ الشراء")),
                (
                    "warranty_expiry",
                    models.DateField(verbose_name="تاريخ انتهاء الضمان"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "نشط"),
                            ("maintenance", "صيانة"),
                            ("broken", "معطل"),
                            ("retired", "متقاعد"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment",
                        to="hospitals.department",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment",
                        to="hospitals.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "معدات",
                "verbose_name_plural": "المعدات",
            },
        ),
        migrations.AddField(
            model_name="department",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="hospitals.hospital",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("hospital", "name")},
        ),
    ]
