# Generated by Django 5.1.4 on 2025-01-05 14:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import accounts.validators


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_role_staff_nurse"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "مستخدم",
                "verbose_name_plural": "المستخدمين",
            },
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="profile_image",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاريخ الميلاد"),
        ),
        migrations.AddField(
            model_name="user",
            name="blood_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                ],
                max_length=3,
                verbose_name="فصيلة الدم",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="المدينة"),
        ),
        migrations.AddField(
            model_name="user",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="اسم الشركة"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاريخ الإنشاء"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم الإنشاء بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الحذف"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم الحذف بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="experience_years",
            field=models.PositiveIntegerField(default=0, verbose_name="سنوات الخبرة"),
        ),
        migrations.AddField(
            model_name="user",
            name="father_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="اسم الأب"),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "ذكر"), ("F", "أنثى")],
                default="M",
                max_length=1,
                verbose_name="الجنس",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="id_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[accounts.validators.validate_syrian_id],
                verbose_name="رقم الهوية",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="id_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="id_pictures/",
                verbose_name="صورة الهوية",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="id_type",
            field=models.CharField(
                choices=[
                    ("national_id", "الهوية الوطنية"),
                    ("passport", "جواز سفر"),
                    ("military_id", "الهوية العسكرية"),
                    ("residence", "إقامة"),
                ],
                default="national_id",
                max_length=20,
                verbose_name="نوع الهوية",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="محذوف"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="تم التحقق"),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login_ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="آخر عنوان IP"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_modified_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="license_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[accounts.validators.validate_medical_license],
                verbose_name="رقم الترخيص",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="license_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="license_pictures/",
                verbose_name="صورة الترخيص",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "أعزب/عزباء"),
                    ("married", "متزوج/ة"),
                    ("divorced", "مطلق/ة"),
                    ("widowed", "أرمل/ة"),
                ],
                max_length=10,
                verbose_name="الحالة الاجتماعية",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="mother_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="اسم الأم"),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pictures/",
                verbose_name="الصورة الشخصية",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="qualification",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="المؤهل العلمي"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="region",
            field=models.CharField(blank=True, max_length=100, verbose_name="المنطقة"),
        ),
        migrations.AddField(
            model_name="user",
            name="registration_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="رقم السجل التجاري"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="specialty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("general", "طب عام"),
                    ("cardiology", "قلبية"),
                    ("dermatology", "جلدية"),
                    ("neurology", "عصبية"),
                    ("orthopedics", "عظمية"),
                    ("pediatrics", "أطفال"),
                    ("psychiatry", "نفسية"),
                    ("ophthalmology", "عيون"),
                    ("dentistry", "أسنان"),
                    ("surgery", "جراحة عامة"),
                    ("gynecology", "نسائية وتوليد"),
                    ("urology", "بولية"),
                    ("ent", "أنف وأذن وحنجرة"),
                    ("internal", "داخلية"),
                ],
                max_length=50,
                verbose_name="التخصص",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تم التحديث بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "مدير النظام"),
                    ("doctor", "طبيب"),
                    ("patient", "مريض"),
                    ("pharmacy", "صيدلية"),
                    ("lab", "مختبر"),
                    ("hospital", "مستشفى"),
                    ("insurance", "شركة تأمين"),
                    ("staff", "موظف"),
                    ("nurse", "ممرض/ة"),
                ],
                default="patient",
                max_length=20,
                verbose_name="نوع المستخدم",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ التحقق"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, verbose_name="العنوان"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="البريد الإلكتروني",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="الاسم الأول"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="الاسم الأخير"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[accounts.validators.validate_phone_number],
                verbose_name="رقم الهاتف",
            ),
        ),
    ]
